Notebook
Steps
Data Exploration
Univariante analysis 
Bivariante analysis

```{r}
#read the dataset
file=readRDS("loan_data_1.rds")

```


```{r}
#create frame for dataset
credit_frame=data.frame(file)
```

```{r}
  str(credit_frame)   
```
```{r}
       
   head(credit_frame)
```


```{r}
        sapply(credit_frame,function(x) sum(is.na(x)))
```
```{r}
     library(gmodels)
    CrossTable(credit_frame$loan_status)

```
```{r}
print(summary(credit_frame$loan_amnt))
print(summary(credit_frame$int_rate))
print(summary(credit_frame$emp_length))
```














```{r}
library(gmodels)
CrossTable(credit_frame$loan_status)

CrossTable(credit_frame$grade)
CrossTable(credit_frame$home_ownership)


```
```{r}
library(ggplot2)
plot(credit_frame$annual_inc,ylab="Loan Amount")


```

```{r}
index_outlier_annua_inc<-which(credit_frame$annual_inc>3000000)
index_outlier_annua_inc
nrow(credit_frame)
credit_frame<-credit_frame[-index_outlier_annua_inc,]
nrow(credit_frame)

```

```{r}
plot(credit_frame$annual_inc,ylab="Loan Amount")

```

```{r}
hist(credit_frame$annual_inc,sqrt(nrow(credit_frame)))
```
```{r}
plot(credit_frame$emp_length,ylab = "age")
```
```{r}
index_emp_len_NA<-which(is.na(credit_frame$emp_length))
credit_frame$emp_length[index_emp_len_NA]<-mean(credit_frame$emp_length,na.rm = TRUE)


```

```{r}
summary(credit_frame$int_rate)
index_int_rate_NA<-which(is.na(credit_frame$int_rate))
credit_frame$int_rate[index_int_rate_NA]<-mean(credit_frame$int_rate,na.rm = TRUE)
summary(credit_frame$int_rate)
```


